# Chapter 1: Introduction to Deep Learning with PyTorch

## 1. What is PyTorch?
PyTorch is an open-source machine learning library developed by Facebook's AI Research lab. It provides:
- Tensor computation (like NumPy) with strong GPU acceleration
- Deep neural networks built on a tape-based autograd system
- Easy-to-use API for building and training neural networks

## 2. Tensors: The Building Blocks
**Tensors** are multi-dimensional arrays that store data. They are the fundamental data structure in PyTorch.

### Creating Tensors
- Use `torch.tensor()` to create a tensor from a Python list
- Tensors can be 1D (vector), 2D (matrix), or higher dimensional

### Example:
```python
temperature = [[43, 45, 21], [65, 87, 98]]
temp_tensor = torch.tensor(temperature)
```
This creates a 2D tensor (2 rows, 3 columns)

## 3. Tensor Operations
PyTorch supports element-wise operations on tensors:
- **Addition**: `tensor1 + tensor2`
- **Subtraction**: `tensor1 - tensor2`
- **Multiplication**: `tensor1 * tensor2`
- **Division**: `tensor1 / tensor2`

**Note**: Tensors must have compatible shapes for operations

## 4. Neural Network Basics

### 4.1 Linear Layer (nn.Linear)
A **Linear Layer** performs a linear transformation: `y = xW^T + b`
- `W` = weight matrix
- `b` = bias vector
- `x` = input tensor

**Syntax**: `nn.Linear(in_features, out_features)`
- `in_features`: size of input
- `out_features`: size of output

### Example:
```python
linear_layer = nn.Linear(in_features=3, out_features=2)
```
This layer takes 3 inputs and produces 2 outputs

### 4.2 Sequential Models
`nn.Sequential` allows you to stack multiple layers to create a neural network.

```python
model = nn.Sequential(
    nn.Linear(8, 4),  # Input: 8, Output: 4
    nn.Linear(4, 1)   # Input: 4, Output: 1
)
```

## 5. Model Parameters
Every neural network layer has **parameters** (weights and biases) that are learned during training.

### Counting Parameters
Use `.parameters()` to iterate through all parameters:
```python
total = 0
for p in model.parameters():
    total += p.numel()  # numel() returns number of elements
```

### Parameter Calculation:
For a Linear layer with `in_features=m` and `out_features=n`:
- **Weights**: `m × n` parameters
- **Bias**: `n` parameters
- **Total**: `(m × n) + n = n(m + 1)` parameters

### Example Calculation:
```
Layer 1: nn.Linear(8, 4) → 8×4 + 4 = 36 parameters
Layer 2: nn.Linear(4, 1) → 4×1 + 1 = 5 parameters
Total: 36 + 5 = 41 parameters
```

## 6. Key Concepts Summary
1. **Tensors** are the core data structure in PyTorch
2. **nn.Linear** creates fully connected layers
3. **nn.Sequential** chains layers together
4. **Parameters** are the learnable weights in the network
5. PyTorch uses **dynamic computation graphs** (define-by-run)

## 7. Important Methods
- `torch.tensor()`: Create a tensor
- `torch.Tensor()`: Create a tensor (alternative constructor)
- `.numel()`: Count elements in a tensor
- `.parameters()`: Access model parameters
- `nn.Linear()`: Create a linear transformation layer
- `nn.Sequential()`: Stack layers sequentially

## Example 1: Creating and Manipulating Tensors

This example demonstrates:
- **Creating tensors from Python lists** using `torch.tensor()`
- **Tensor addition** - Adding two tensors element-wise
- **Output**: Shows the original tensor and the result of addition

**Key Learning**: Tensors can perform vectorized operations, which are much faster than regular Python loops.

In [4]:
import torch
import torch.nn as nn

temperature = [[43, 45, 21], [65, 87, 98]]

temp_tensor = torch.tensor(temperature)
print(temp_tensor)

adjusted_temp = torch.tensor([[2, 2, 3], [2, 4, 5]])

addition_result = temp_tensor + adjusted_temp
print(addition_result)

tensor([[43, 45, 21],
        [65, 87, 98]])
tensor([[ 45,  47,  24],
        [ 67,  91, 103]])


## Example 2: Linear Layer Transformation

This example shows:
- **Creating a linear layer** with `nn.Linear(in_features=3, out_features=2)`
- **Input tensor**: 1 sample with 3 features
- **Output tensor**: 1 sample with 2 features (transformed)
- The layer applies the formula: `output = input × W^T + b`

**Key Learning**: Linear layers are the building blocks of neural networks. They transform data from one dimension to another using learnable weights and biases.

In [7]:
input_tensor = torch.tensor([[0.3471, 0.4547, -0.2356]])

linear_Layer = nn.Linear(in_features=3, out_features=2)

output = linear_Layer(input_tensor)
print(output)

tensor([[-0.1064, -0.3833]], grad_fn=<AddmmBackward0>)


## Example 3: Building a Multi-Layer Neural Network

This example demonstrates:
- **Creating a sequential model** with multiple layers
- **First layer**: Transforms 8 inputs → 4 outputs
- **Second layer**: Transforms 4 inputs → 1 output
- **nn.Sequential**: Automatically connects layers so output of one layer feeds into the next

**Key Learning**: Deep neural networks are created by stacking multiple layers. Data flows through each layer sequentially, getting transformed at each step.

In [8]:
# My First Neural Network

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

model = nn.Sequential(
    nn.Linear(8, 4),
    nn.Linear(4, 1)
)

output = model(input_tensor)
print(output)



tensor([[-2.9243]], grad_fn=<AddmmBackward0>)


## Example 4: Counting Model Parameters

This example shows:
- **Iterating through parameters** using `model.parameters()`
- **Counting elements** with `.numel()` (number of elements)
- **Total parameters**: Sum of all weights and biases in the model

**Calculation breakdown**:
- Layer 1 (8→4): (8×4) + 4 = 36 parameters
- Layer 2 (4→1): (4×1) + 1 = 5 parameters
- **Total**: 41 parameters

**Key Learning**: Understanding parameter count helps you estimate model size, memory requirements, and training complexity. More parameters = more capacity to learn, but also more risk of overfitting.

In [9]:
# Calculate the number of parameters in the model

total = 0

for p in model.parameters():

    total += p.numel()

print(f'Total number of parameters in the model: {total}')

Total number of parameters in the model: 41
